### ISSUE TITLE
Can you add linux support ?

### ISSUE THREAD

**Issue by syrm** [chunqian/go-raylib#1]
Hello, 

Thank you for your great work.
Can you add linux support please ?

**Comment by chunqian** [comment]
@syrm
I don't have a linux machine for now.
I will make go-raylib support linux.

**Comment by makew0rld** [comment]
@chunqian any update on this? I think [this file](https://github.com/gen2brain/raylib-go/blob/master/raylib/cgo_linux.go) might be helpful in adding Linux support. I would be happy to test for you. Creating a Linux virtual machine for testing should also be pretty easy.

**Comment by chunqian** [comment]
@syrm @makeworld-the-better-one

**Comment by chunqian** [comment]
@syrm @makeworld-the-better-one 
go-raylib has support linux, test well on xubuntu 16.04.
