### ISSUE TITLE
Custom raylib build

### ISSUE THREAD

**Issue by hismailbulut** [chunqian/go-raylib#12]
Is there a way to use custom build of raylib. Or much better surround definitions in config.h file with ifndef flags and we can define custom options from CGO_CFLAGS

**Comment by chunqian** [comment]
Ok
Let me see.

**Comment by chunqian** [comment]
@hismailbulut 
```shell
CGO_CFLAGS='-DSUPPORT_VR_SIMULATOR=0 -DSUPPORT_EVENTS_WAITING=1' go build
```
This turn off vr support and turn on event polling
define as 0 is turn off
define as 1 is turn on

**Comment by chunqian** [comment]
@hismailbulut
```shell
CGO_CFLAGS='-DSUPPORT_VR_SIMULATOR=0 -DSUPPORT_EVENTS_WAITING=1' go build
```
This turn off vr support and turn on event polling
I have add ifndef flags in config.h file

**Comment by hismailbulut** [comment]
Thank you for your effort.

**Comment by hismailbulut** [comment]
Actually this still doesn't work. I am using this makefile:
```Makefile
SOURCEFOLDER=./cmd/neoray
EXECUTABLE=bin/neoray.exe
export CGO_CFLAGS=-g -O2 -DSUPPORT_DEFAULT_FONT=0 -DSUPPORT_SCREEN_CAPTURE=0
build:
    go build -o ${EXECUTABLE} -race ${SOURCEFOLDER}
run: build
    ./${EXECUTABLE}
```
I can see the CGO_CFLAGS is has these flags when I type 'go env'. It compiles without warnings but both of them not working.
Default font loading and screen capture is still works. This is an example all flags isn't working.
Library is up to date. I confirm there is ifndef flags in config.h file. I am using Windows 10.

**Comment by chunqian** [comment]
Let's see
I only tested macos before

**Comment by chunqian** [comment]
@hismailbulut 
Now fixed.

**Comment by hismailbulut** [comment]
Yes it's working. Thank you.
