### ISSUE TITLE
possible memory leaks?

### ISSUE THREAD

**Issue by ghost** [chunqian/go-raylib#13]
Hey, this is my first issue on Github, so bear with me...
I've been playing around with Raylib using pure interop with Swift language. As a comparison, I wanted to check for memory leaks against Go (which is a language I'm familiar with), and I found something interesting.

No matter what code it would be, you could use an example provided, and you would get similar or the same memory loss/leak.
I will go straight to the point.

[Memory Check with Valgrind](https://gist.github.com/conifer-dev/0da01a5149e55b8440a754364ad8db90)
If you check out the gist linked above, you can see that around 40,015 bytes in 573 blocks are possibly lost in go-raylib binding vs 0 bytes in 0 blocks against Swift's pure interop to C without any safe pointer management etc. 

I did post this on raylib discord server under Go's channel, but I take it you aren't on the server? So I didn't know if it was worth posting it here either or not and find out what exactly is going on. Is it the binding that is leaking memory or something else?

Thanks!

**Comment by chunqian** [comment]
Sorry, I'm not on that server
I'll take a look at Valgrind Memory Check today and I'll find out why

**Comment by chunqian** [comment]
@conifer-dev 
tools like valgrind don’t understand Go’s calling conventions or stack layout.

**Comment by chunqian** [comment]
```go
package main

// #include <stdio.h>
// #include <stdlib.h>
//
// static void myprint(char* s) {
//   printf("%s\n", s);
// }
import "C"
import "unsafe"

func main() {
  cs := C.CString("Hello from stdio")
  C.myprint(cs)
  C.free(unsafe.Pointer(cs))
}
```

```bash
valgrind test
==16236== LEAK SUMMARY:
==16236==    definitely lost: 0 bytes in 0 blocks
==16236==    indirectly lost: 0 bytes in 0 blocks
==16236==      possibly lost: 1,152 bytes in 4 blocks
==16236==    still reachable: 0 bytes in 0 blocks
==16236==         suppressed: 0 bytes in 0 blocks
==16236== Rerun with --leak-check=full to see details of leaked memory
```

```go
package main

// #include <stdio.h>
// #include <stdlib.h>
//
// static void myprint(char* s) {
//   printf("%s\n", s);
// }
import "C"
// import "unsafe"

func main() {
  cs := C.CString("Hello from stdio")
  C.myprint(cs)
  // C.free(unsafe.Pointer(cs))
}
```

```bash
==16452== LEAK SUMMARY:
==16452==    definitely lost: 17 bytes in 1 blocks
==16452==    indirectly lost: 0 bytes in 0 blocks
==16452==      possibly lost: 1,152 bytes in 4 blocks
==16452==    still reachable: 0 bytes in 0 blocks
==16452==         suppressed: 0 bytes in 0 blocks
==16452== Rerun with --leak-check=full to see details of leaked memory
```

tools like valgrind don’t understand Go’s calling conventions or stack layout.

golang use cgo, valgrind's possibly lost is useless.

**Comment by ghost** [comment]
Thanks for clearing that up! That makes more sense.
