### ISSUE TITLE
macOS warning - Implicit conversion of int to float

### ISSUE THREAD

**Issue by ghost** [chunqian/go-raylib#14]
Hi,

Recently found this warning popping up regarding implicit conversion of int to float from within go-raylib:

`github.com/chunqian/go-raylib/raylib
In file included from ../../../../../pkg/mod/github.com/chunqian/go-raylib@v0.0.0-20210503031118-b870b50292b9/raylib/raylib_darwin.go:11:
In file included from ../../../../../pkg/mod/github.com/chunqian/go-raylib@v0.0.0-20210503031118-b870b50292b9/raylib/../lib/raylib/src/models.c:89:
../../../../../pkg/mod/github.com/chunqian/go-raylib@v0.0.0-20210503031118-b870b50292b9/raylib/../lib/raylib/src/external/par_shapes.h:1055:32: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-const-int-float-conversion]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:105:18: note: expanded from macro 'RAND_MAX'`

**Comment by chunqian** [comment]
Operating System Information？

**Comment by chunqian** [comment]
I don't have this warning on my macbook pro
this warning , use steps?

**Comment by ghost** [comment]
> I don't have this warning on my macbook pro
> this warning , use steps?

Using macOS Big Sur 11.4 Beta 3
The warning does not show up on Linux nor Windows.

Not connected to my code, even happens with examples from github

**Comment by chunqian** [comment]
That all 32-bit int values from 2147483584 to 2147483647 will be rounded up to a float value of 2147483648.
The largest int value that will round down is 2147483583, which the same as (INT_MAX - 64) on a 32-bit system.

**Comment by chunqian** [comment]
maybe macOS Beta problem
macOS official version no warning

**Comment by chunqian** [comment]
Fixed.
You can test it.

**Comment by ghost** [comment]
That's fixed!
