### ISSUE TITLE
Trouble installing package

### ISSUE THREAD

**Issue by nonunknown** [chunqian/go-raylib#15]
So I'm trying to import it but with no success:

![image](https://user-images.githubusercontent.com/58845030/119348088-c6a61980-bc72-11eb-8068-16e7a4a69aa8.png)

the go.mod:
![image](https://user-images.githubusercontent.com/58845030/119348166-dd4c7080-bc72-11eb-8423-eb2d1f0e8d79.png)

if I run `go mod tidy`:
```
go: finding module for package github.com/chunqian/go-raylib
github.com/jeedee/kobu-server imports
        github.com/chunqian/go-raylib: module github.com/chunqian/go-raylib@latest found (v0.0.0-20210519095144-df36dae46c76), but does not contain package github.com/chunqian/go-raylib
```

**Comment by chunqian** [comment]
@nonunknown 
import
```go
import (
    rl "github.com/chunqian/go-raylib/raylib"
)
```
not
```go
import (
    rl "github.com/chunqian/go-raylib"
)
```

**Comment by nonunknown** [comment]
ok I'll try and tell you

**Comment by nonunknown** [comment]
yeah it worked, but it has another problem: #16
