### ISSUE TITLE
Running `go build` throws error

### ISSUE THREAD

**Issue by nonunknown** [chunqian/go-raylib#16]
![image](https://user-images.githubusercontent.com/58845030/119489527-2a434c00-bd32-11eb-9b1a-b8d476acffed.png)

Note: I'm using `go mod vendor` which brings files to workspace folder:

![image](https://user-images.githubusercontent.com/58845030/119489755-65de1600-bd32-11eb-8f1e-4b76a54e111b.png)

edit: I was messing with the local files, seems to be a problem with `cgo` package?

![image](https://user-images.githubusercontent.com/58845030/119492506-89569000-bd35-11eb-9b42-1118a8af2577.png)

Also according to the error message on the build process the file `rglfw.c` wasnt found, but I could find it here, just dont know how go does to find it:

![image](https://user-images.githubusercontent.com/58845030/119492793-dcc8de00-bd35-11eb-9ff6-27aa7cdd3f99.png)

IMPORTANT: This also happens on Linux (even after installing those packages: `apt-get install libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev `)

**Comment by chunqian** [comment]
I did not use vendor, I'll look at the later

**Comment by nonunknown** [comment]
ok, I would like to get some help , cause my job depends on this! I'm trying to running it on the server side, so `go vendor` is required!

**Comment by nonunknown** [comment]
So, I think I found the possible solution for this problem, seems its 100% related to path on the `#include` stuff, seems that the includes cant reach this folder:

![image](https://user-images.githubusercontent.com/58845030/119511881-38509700-bd49-11eb-9658-1d4592b00d17.png)

`go\pkg\mod\github.com\chunqian\go-raylib@v0.0.0-20210519095144-df36dae46c76\lib\raylib\src`

**Comment by chunqian** [comment]
@nonunknown 
`go mod vendor` not support cgo, see this [#1571](https://github.com/golang/go/issues/26366)
use [vend](https://github.com/nomad-software/vend) instead of `go mod vendor`

**Comment by nonunknown** [comment]
WOW, it has worked like a glove in a hand! thanks @chunqian
