### ISSUE TITLE
Why update raylib?

### ISSUE THREAD

**Issue by makew0rld** [chunqian/go-raylib#5]
Why did you update the raylib library in c620d8c289cee96507ee311e1cc87d2ae1a5ed5d? Shouldn't this code stick to the 3.5 release? 3.6-dev will update frequently and have bugs, it's not ready yet.

**Comment by chunqian** [comment]
I ignored
Enable main
I will make some changes in the dev

**Comment by makew0rld** [comment]
Okay so only use the main branch? And you've rolled back the raylib update in c810615?

**Comment by chunqian** [comment]
Yes
The main branch will keep up to date with the latest raylib c release version
