### ISSUE TITLE
Error running gui examples on Windows 10

### ISSUE THREAD

**Issue by uSources** [chunqian/go-raylib#6]
OS: Windows 10

Im try to test gui examples, but throws 

C:/Users/usour/go/pkg/mod/github.com/chunqian/go-raylib@v0.0.0-20210324031449-14c8ddf0f580/lib/raygui/src/raygui.h:3196: multiple definition of `GuiCheckIconPixel'
C:\Users\usour\AppData\Local\Temp\go-build1291992362\b038\_x002.o:C:/Users/usour/go/pkg/mod/github.com/chunqian/go-raylib@v0.0.0-20210324031449-14c8ddf0f580/lib/raygui/src/raygui.h:3196: first defined here

I recompiled raylib including physac and raygui , but throws the same error.

What could be ?

**Comment by chunqian** [comment]
@uSources
I fixed.
